---
name: CLI Applications
shards:
- github: caravel-tool/caravel
- github: crystallabs/crystime
  description: Advanced time, calendar, schedule, and remind library for Crystal
- github: askn/fikri
  description: Simple CLI To-Do App
- github: jhass/github_desktop_notifications
- github: tbrand/mssh
  description: Simple and powerful job executor on remote nodes
- github: mjago/sonicri
- github: sferik/spellout
  description: A command-line tool that converts input into the International Radiotelephony
    Spelling Alphabet
- github: porras/tlcr
  description: Simple terminal-based client for TLDR
- github: geolessel/trello-cli
  description: It's Trello, but snappy
- github: mamantoha/zipstream
  description: A command line tool that allows you to easily share files and directories
    over the network
