---
name: CLI Applications
shards:
- github: askn/fikri
  description: Simple CLI To-Do App
- github: tbrand/mssh
  description: Simple and powerful job executor on remote nodes
- github: mamantoha/zipstream
  description: A command line tool that allows you to easily share files and directories
    over the network
